language: android
jdk: openjdk7
android:
  components:
    - build-tools-19.1.0
    - android-19
    - extra-android-support
    - extra-android-m2repository
    - sysimg-19
  licenses:
    - '.+'
script:
  - ./gradlew connectedAndroidTest

